name: When approve merge to Integration

on:
  pull_request_review:
    types: [submitted]
  workflow_dispatch:
      inputs:
          pull-request:
              description: Pull Request Number
              required: false

concurrency: integration

env: 
  BASE_BRANCH:

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - name: Variables
        run: echo "hola  ${{github.event.pull_request}}  ${{github.event.review.state}}" 
  merge:
    name: Merge into stage
    if: github.event.review.state == 'approved' && contains(github.event.pull_request.labels.*.name, 'QA' )
    runs-on: ubuntu-latest
    steps:
      # Environment variables
      - name: Extract branch name
        run: echo "BASE_BRANCH=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV

      - name: Extract branch URI
        run: echo "BASE_BRANCH_URI=${BASE_BRANCH/\#/%2F%23} >> $GITHUB_ENV

      - name: Debug
        run: |
          echo $BASE_BRANCH
          echo $BASE_BRANCH_URI
      
      # Merge step
      - name: Merge ${{ env.BASE_BRANCH }} into stage
        uses: octokit/request-action@v2.x
        id: merge
        with:
          route: POST /repos/:repository/merges
          repository: ${{ github.repository }}
          ref: ${{ env.BASE_BRANCH }}
          head: ${{ env.BASE_BRANCH }}
          base: stage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Add comment to PR
        uses: mshick/add-pr-comment@v2
        with:
          message: |
              ## PR has been merged into stage

              - ✅ Your can review the changes on the [stage site](https://antares-blog-stage-${{ env.BASE_BRANCH_URI }}.azurewebsites.net)
          