name: DEV 001 - Add QA Validation Comment

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  labels-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v3
        with:
          script: |
            const script = require(`${process.env.GITHUB_WORKSPACE}/.github/workflows/scripts/check-labels.cjs`)
            script({github, context})

  add-comment:
    if: contains(github.event.pull_request.labels.*.name, 'QA')
    runs-on: ubuntu-latest
    needs: labels-check
    steps:
    - name: Add comment to PR
      uses: mshick/add-pr-comment@v2
      with:
        message-path: |
            messages/message-cr-ok.txt
             
        allow-repeats: true
        # message: |
        #     ## [Preview link](https://antares-blog-staging-pr-${{ github.event.number }}.azurewebsites.net)

        #     - ✅ PR creada correctamente se puede revisar ya a nivel de código 
        #     > *This is an automated message.*
        # message-failure: |
        #     Uh oh!
        # repo-token: ${{ secrets.GITHUB_TOKEN }}
        # allow-repeats: true